[package]
authors = ["Jonathan 'theJPster' Pallant <github@thejpster.org.uk>"]
edition = "2018"
resolver = "2"
readme = "README.md"
license = "GPL-3.0-or-later"
name = "neotron-pico-bios"
version = "0.7.0"

[dependencies]
chrono = { version = "0.4.38", default-features = false } # Calendar/Date/Time functions and types 
cortex-m = {version = "0.7", features = ["inline-asm"]} # Useful Cortex-M specific functions (e.g. SysTick)
cortex-m-rt = "0.7" # Cortex-M run-time (or start-up) code
critical-section = "1.0" # Hardware locks for sharing data with interrupts
defmt = "0.3" # Gives us formatted PC-side logging
defmt-rtt = "0.4" # Sends defmt logs to the SWD debugger
ds1307 = "0.5.0" # The Dallas DS1307 RTC driver
embedded-hal = "0.2" # For hardware abstraction traits
embedded-sdmmc = { version = "0.6", default-features = false, features = [ "defmt-log" ] } # SD Card driver
fugit = "0.3" # Time and frequency related functions
grounded = { version = "0.2.0", features = ["critical-section"] }
heapless = "0.7" # Useful queues and other structures
mcp794xx = "0.3.0" # The Microchip MCP7940x RTC driver
neotron-bmc-commands = { version = "0.2.0" } # Commands for talking to a Neotron BMC. The tag is for the repo as a whole, of which the commands crate is a small part.
neotron-bmc-protocol = { version = "0.1.0", features = ["defmt"] } # Protocol for talking to a Neotron BMC. The tag is for the repo as a whole, of which the protocol crate is a small part.
neotron-common-bios = "0.12.0" # The BIOS to OS API
panic-probe = "0.2" # Send panics to the debugger
pc-keyboard = "0.7.0" # PS/2 scancode decoding
pio = "0.2.1" # RP2040 PIO assembler
pio-proc = "0.2" # Macros for RP2040 PIO assembler
portable-atomic = { version = "1.10.0", features = ["critical-section"] } # Atomic CAS for non-CAS CPUs
rp2040-boot2 = "0.3.0" # For the RP2040 bootloader
rp2040-hal = { version = "0.11", features = [ "defmt", "rt", "critical-section-impl", "rom-func-cache" ] } # The Raspberry Pi RP2040 HAL (so we can turn defmt on)
shared-bus = "0.3.1" # I2C Bus Sharing
tlv320aic23 = "0.1.0" # CODEC register control

[build-dependencies]
neotron-common-bios = "0.12.0"
vte = "0.11"

[[bin]]
name = "neotron-pico-bios"
test = false
bench = false

[profile.release]
# better optimizations
codegen-units = 1
# symbols are nice and they don't increase the size on Flash
debug = true
# better optimizations
lto = true
# Set the optimisation level to optimise for space. This also happens to be a
# good choice for performance on the RP2040, where code executes from external
# SPI Flash and has to be buffered in a small on-chip cache memory.
opt-level = "s"

[features]
check-stack = []
