on: [push, pull_request]
name: Build (and Release)

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (and Release)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
          fetch-depth: 0

      - name: Add targets
        run: |
          rustup target add thumbv6m-none-eabi

      - name: Build neotron-pico-bios
        run: |
          cargo build --release --verbose

      - name: Upload files to Release
        if: github.event_name == 'push' && startswith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./target/thumbv6m-none-eabi/release/neotron-pico-bios
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}