on: [push, pull_request]
name: Build (and Release)

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    name: Build (and Release)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Install tools
        uses: taiki-e/install-action@v2
        with:
          tool: elf2uf2-rs@2.0.0

      - name: Add targets
        run: |
          rustup target add thumbv6m-none-eabi

      - name: Build neotron-pico-bios
        run: |
          cargo build --release --verbose
          elf2uf2-rs ./target/thumbv6m-none-eabi/release/neotron-pico-bios

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        if: ${{success()}}
        with:
          name: Artifacts
          if-no-files-found: error
          path: |
            ./target/thumbv6m-none-eabi/release/neotron-pico-bios
            ./target/thumbv6m-none-eabi/release/neotron-pico-bios.uf2

      - name: Upload files to Release
        if: github.event_name == 'push' && startswith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          files: |
            ./target/thumbv6m-none-eabi/release/neotron-pico-bios
            ./target/thumbv6m-none-eabi/release/neotron-pico-bios.uf2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}