name: Clippy

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always

jobs:
  clippy-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0

      - name: Add targets/components
        run: |
          rustup component add clippy
          rustup target add thumbv6m-none-eabi

      - name: Run Clippy
        run: |
          cargo clippy --target=thumbv6m-none-eabi --all-features
